# Generated by Django 2.2.5 on 2019-09-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_auto_20190927_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
    ]
